SpiNNakerManchester/spalloc

spalloc/__init__.py
spalloc/protocol_client.py
spalloc/scripts/alloc.py
spalloc/scripts/job.py
spalloc/scripts/machine.py
spalloc/scripts/ps.py
spalloc/scripts/support.py
spalloc/scripts/where_is.py
tests/scripts/test_job_script.py
tests/scripts/test_machine.py
tests/scripts/test_ps.py
tests/scripts/test_where_is.py
tests/test_protocol_client.py

This fixes the user-visible scripts for spalloc to be more pythonic and to be aware of the changes to the spalloc protocol.

Script rewrite

---

spalloc/protocol_client.py

Resolve intermittent threading bug. https://github.com/SpiNNakerManchester/spalloc/issues/12
I'm not quite sure how to induce the bug reliably, but a reliable fix is to control the initialisation of the thread locals so that each thread gets its state well-defined.

Resolve intermittent threading bug.

---

requirements-docs.txt
requirements.txt
setup.py

This adds future to the requirements of spalloc.  I think I got everything, but doing a pull request in case not

Add future

---

spalloc/_keepalive_process.py
spalloc/config.py
spalloc/job.py
spalloc/protocol_client.py
spalloc/scripts/alloc.py
spalloc/scripts/job.py
spalloc/scripts/machine.py
spalloc/scripts/ps.py
spalloc/scripts/support.py
spalloc/scripts/where_is.py
spalloc/term.py
tests/conftest.py
tests/scripts/test_alloc.py
tests/scripts/test_job_script.py
tests/scripts/test_machine.py
tests/scripts/test_ps.py
tests/scripts/test_where_is.py
tests/test_config.py
tests/test_job.py
tests/test_protocol_client.py
tests/test_term.py

https://www.python.org/dev/peps/pep-0328/#rationale-for-parentheses

Make import statements use PEP 328 better

---

.travis.yml
docs/source/conf.py
requirements-test.txt

Part of https://github.com/SpiNNakerManchester/SpiNNUtils/issues/75

Enable testing with Python 3.7

---

spalloc/job.py
spalloc/protocol_client.py
spalloc/scripts/alloc.py
spalloc/scripts/job.py
spalloc/scripts/machine.py
spalloc/scripts/where_is.py
spalloc/term.py
tests/test_term.py

Part of https://github.com/SpiNNakerManchester/SpiNNUtils/issues/75

Deprication Warnings

---

tests/test_protocol_client.py

Merging in 5...4...3...2...1...

Fix for change in Pytest

---

spalloc/job.py
spalloc/protocol_client.py
spalloc/scripts/alloc.py
spalloc/scripts/job.py
spalloc/scripts/machine.py
spalloc/scripts/where_is.py
spalloc/term.py
tests/test_term.py

https://github.com/SpiNNakerManchester/SpiNNUtils/issues/102

fixed incorrect import from collections.abc

---

spalloc/config.py
spalloc/scripts/support.py

Add option to ignore server version in case of emergency!
Also update the current version compatibility, which was out-of-date.

Ignore version

---

.travis.yml
setup.py
spalloc/config.py

Also run each version with best choice of Ubuntu distribution

Add testing with Python 3.8

---

.travis.yml
pytest.ini
requirements.txt
setup.py
spalloc/protocol_client.py
spalloc/scripts/alloc.py

Also shut up some stupid warnings from rig; we're not fixing them anyway

Use the AbstractContextManager from SpiNNUtils

---

.github/workflows/python_actions.yml
requirements-docs.txt
requirements.txt
setup.py
spalloc/_keepalive_process.py
spalloc/config.py
spalloc/protocol_client.py
spalloc/scripts/alloc.py
spalloc/scripts/job.py
spalloc/scripts/machine.py
spalloc/scripts/support.py
spalloc/term.py
tests/scripts/test_alloc.py
tox.ini

PyPI and pip are forcing the issue; we can't keep going much longer.
SpiNNakerManchester/SpiNNUtils#132

Remove Python 2.7 support

---

spalloc/job.py
spalloc/scripts/machine.py

We only need one version range...

One version (range)

---

.pylintrc
spalloc/__init__.py

Similar to https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/946 but removes a lot more disables.
removes # noqa: or makes then specific

Pylint fix

---

.github/workflows/python_actions.yml
setup.py

Drop python 3.6 as described in https://github.com/SpiNNakerManchester/SupportScripts/pull/43

Remove 3.6

---

spalloc/scripts/support.py

Allows the old client to talk to the compatibility interface of the new server.
It's a bit of a hack, of course.

Server rewrite adaptation 

---

setup.cfg

Adds the spalloc command entry points back in so these can be used from command line

Add entry points back in

---

setup.cfg
spalloc_client/_version.py

Part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/236

Version bump

---

.readthedocs.yaml

did not work so updated yml.
now works

Readthedocs fix

---

spalloc_client/scripts/job.py
tests/test_doc_checker.py

part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/321

Improved Doc checker and minor fixes

---

docs/source/conf.py
spalloc_client/_utils.py
spalloc_client/job.py
spalloc_client/protocol_client.py
spalloc_client/scripts/alloc.py
spalloc_client/scripts/job.py
spalloc_client/scripts/machine.py
spalloc_client/scripts/ps.py
spalloc_client/scripts/support.py
spalloc_client/term.py
tests/test_doc_checker.py

There is a mix of doc styles in this repository but fixing that was out of scope of this pr

Docs fixes
